### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by rriemann** [discourse/discourse_docker#121] opened 2015-01-13 10:56 UTC
Can you please have a look into arm support for your docker image. So far it does not work because of x86 dependencies.

Maybe this involves updating other docker files which has to be done upstream. So this is issue to track the progress.

There is a thread in the forum of the online.net arm cloud about this topic: https://community.cloud.online.net/t/discourse-instantapp/452/23

**Comment by Moter8** [comment] 2015-02-23 14:34
:+1: Bump

**Comment by SamSaffron** [comment] 2015-02-23 21:16
hmmm how would we get ARM going? can you have docker to support ARM?

**Comment by m0k1** [comment] 2015-03-23 09:57
@SamSaffron Yea, we got docker working on ARM ... https://community.cloud.online.net/t/getting-started-docker-on-c1-armhf/383. So is there now any future for discourse for arm ?

**Comment by rriemann** [comment] 2015-03-23 10:03
Knowing, that http://labs.online.net/ uses theirself Discourse (http://community.cloud.online.net/) and are in a public beta phase, I'm pretty sure that https://github.com/edouardb from the cloud core team could get you a beta account that someone from Discourse could investigate the current issues.

**Comment by edouardb** [comment] 2015-03-23 10:46
Hi there,
Yes we have docker running on our ARM servers and we would love to have the discourse docker install running on them.
There is an issue with therubyracer gem which do not run properly on ARM arch (https://github.com/cowboyd/therubyracer/issues/317) and prevented us to create a clean discourse install. We had to build the libv8 gem with custom flags to get it works on the servers.

To get an access, just let me know and I'll send your an invite.

**Comment by SamSaffron** [comment] 2015-03-23 23:06
@edouardb I would love to support arm but we need to push to get rubyracer fixed first, any chance you could assist with a PR to rubyracer or libv8 to correct this, I know @cowboyd would be more than happy to get this fixed.

**Comment by cowboyd** [comment] 2015-03-24 14:36
looping in @ignisf as the primary libv8 guru. I know he's done reams of work to get libv8 compiling on ARM.

**Comment by edouardb** [comment] 2015-03-25 09:30
@SamSaffron I will

**Comment by edouardb** [comment] 2015-03-27 17:32
Binary gem available for armv7 https://rubygems.org/gems/libv8/versions/3.16.14.8.rc1-armv7l-linux

**Comment by ignisf** [comment] 2015-03-27 17:52
This version should include debugging symbols. So if you experience a segfault again, please provide a full backtraces from both ruby and gdb.

**Comment by m0k1** [comment] 2015-03-29 19:22
Is there anyone working on arm discourse docker image ?

**Comment by rriemann** [comment] 2015-04-02 08:58
I think (hope) @SamSaffron is pushing things forward. :)

**Comment by m0k1** [comment] 2015-04-06 01:07
@SamSaffron Can you give us official statement on this issuse ?

**Comment by SamSaffron** [comment] 2015-04-06 04:10
@m0k1 my official statement ... hmmm 

discourse_docker supports custom base images using `base_image: ` in your container yml. 

Discourse do not have the resources to take on management and maintenance of a x32 image. However we are 100% open to patches that help facilitate this and even directing people at a `contrib` x32 image.

**Comment by ignisf** [comment] 2015-04-08 23:20
@edouardb, @rriemann, @m0k1, did you take the rc of libv8 for a spin? Is it working for you? Should we release it?

**Comment by rriemann** [comment] 2015-04-09 12:07
@ignisf  what do I have to put in the gemfile to give it a try?

**Comment by ignisf** [comment] 2015-04-09 12:09
`gem 'libv8', '~> 3.16.14.8.rc1'`

**Comment by cowboyd** [comment] 2015-04-10 03:55
Please let us know if that version of `libv8` works for you as soon as you get the chance. If so, we'll go ahead and make it generally available.

**Comment by m0k1** [comment] 2015-04-10 08:24
Im still getting this error http://prntscr.com/6rxejk as described here: 
https://community.scaleway.com/t/discourse-instantapp/452/31?u=m0k1
btw i added 
gem 'libv8', '~> 3.16.14.8.rc1'
to Gemfile ...
Is this tutorial wrong or what ? Can some update it if it's not right ...

**Comment by edouardb** [comment] 2015-04-10 15:34
The issue is still present with 3.16.14.8.rc1
I have a libv8 which is working and the version built by @ignisf should be the same. If someone can try it on a C1 node, the gem is online here: https://fr-1.storage.online.net/stuff/libv8_therubyracer.tar

A documentation on how I installed it on an ARM server is available here: https://community.scaleway.com/t/discourse-instantapp/452/31?u=m0k1


@ignisf do you still have access to the node?

**Comment by edouardb** [comment] 2015-04-23 16:03
@SamSaffron Do you think it is possible to remove th therubyracer / libv8 deps and use nodejs instead?

**Comment by SamSaffron** [comment] 2015-04-29 04:29
absolutely not, we need to use therubyracer from in proc, it would be a
very complex change to introduce a new process into the setup.

**Comment by SamSaffron** [comment] 2015-09-14 01:55
I am closing this in favor of a discussion on https://meta.discourse.org

None of this is particularly specific about discourse docker, its about adding arm support to discourse and in particular v8, once that is all working really well it should be trivial to support this from the docker side.... but someone would have to be in charge of making new images ...

**Closed by SamSaffron** 2015-09-14 01:55 UTC

**Comment by ignisf** [comment] 2016-05-17 00:07
Just tested the `mini_racer` runtime on ARM. It seems to be working OK. Have not tested it yet with Discourse, but I'm hopeful.

```
root@scw-52b544:~/mini_racer/benchmark/babel# ruby bench.rb
2546.365301 load babel
mini racer 3712.44014 transform
mini racer 2347.778613 transform
mini racer 2136.142468 transform
mini racer 2130.412053 transform
mini racer 2040.2007740000001 transform
mini racer 2052.423138 transform
mini racer 2022.1824430000001 transform
mini racer 2034.8822910000001 transform
mini racer 2051.778761 transform
mini racer 2039.453886 transform
mini racer 10x 20198.539129 transform
mini racer 10x 20251.828136 transform
mini racer 10x 19734.058504 transform
mini racer 10x 19762.733960999998 transform
mini racer 10x 19584.808633 transform
mini racer 10x 19614.800522999998 transform
mini racer 10x 19431.498847 transform
mini racer 10x 19545.145284 transform
mini racer 10x 19383.841543 transform
mini racer 10x 19421.688061 transform
root@scw-52b544:~/mini_racer/benchmark/exec_js_uglify# bundle exec ruby bench.rb mini_racer
Benching with mini_racer
mini_racer minify discourse_app.js 130981.15443699999ms
mini_racer minify discourse_app_minified.js 165156.036128ms
mini_racer minify discourse_app.js twice (2 threads) 131309.504036ms
root@scw-52b544:~/mini_racer/benchmark/exec_js_uglify# 
```
